Rtd
UtrechtUniversity/iBridges pull request #183
Opened 2024-06-01 17:08 UTC by chStaiger

2024-06-03 14:16 UTC, qubixes requested changes
Nice additions! I have mostly typos for you.

2024-06-04 06:43 UTC, chStaiger commented on docs/source/data_transfers.rst
> +In the example below we transfer a file or a folder to a new collection *new_coll*. The new collection will be created on the fly. Please note, that this is not true for new nested collections.
I changed the wording, gave a hint how to circumvent the error and yes, let's put that on our todo list for the >1.0.0 release.

2024-06-04 06:44 UTC, chStaiger commented on docs/source/data_transfers.rst
> +The new collection will be created on the fly. Please note, that this is not true for new nested collections. Please note that the automatic creation of new collections does not work when they are ne
Done!

2024-06-04 06:47 UTC, chStaiger commented on docs/source/metadata.rst
> +Metadata of dataobjects also have an entry for the checksum. The checksum is ot calculated, but extracted from the iRODS database.
Yes, I rephrased!

2024-06-04 07:34 UTC, merged