Update Tickets class to use datetime as input
UtrechtUniversity/iBridges pull request #40
Opened 2024-02-13 15:26 UTC by qubixes

2024-02-17 10:14 UTC, chStaiger commented on Tutorial_irodsConnector.ipynb
> +    "ticket = tickets.create_ticket(obj_path=objPath, ticket_type=\"write\", expiry_date=datetime.today())  # allow write access"
`"ticket = tickets.create_ticket(obj_path=objPath, ticket_type=\"write\", expiry_date=datetime.date.today() + datetime.timedelta(days=1))  # allow write access"`

2024-02-17 10:15 UTC, chStaiger commented on Tutorial_irodsConnector.ipynb
> +    "ticket = tickets.create_ticket(obj_path=objPath, ticket_type=\"write\", expiry_date=datetime.today())  # allow write access"
```suggestion
    ""ticket = tickets.create_ticket(obj_path=objPath, ticket_type=\"write\", expiry_date=datetime.date.today() + datetime.timedelta(days=1))  # allow write access""
```

2024-02-17 10:24 UTC, chStaiger requested changes
Many thanks, that is indeed much more user-friendly ;). I left a suggestion for even more user-friendlyness. 
I also saw that the unit test on Yoda is failing. Is it possible to get that to work too?

2024-02-18 11:01 UTC, qubixes commented
> Many thanks, that is indeed much more user-friendly ;). I left a suggestion for even more user-friendlyness. I also saw that the unit test on Yoda is failing. Is it possible to get that to work too?

That is basically my question to you. It seems that all tickets are expiring at midnight. Is that the expected/correct behavior? It seems counter-intuitive.

2024-02-18 18:29 UTC, qubixes commented on Tutorial_irodsConnector.ipynb
> +    "ticket = tickets.create_ticket(obj_path=objPath, ticket_type=\"write\", expiry_date=datetime.today())  # allow write access"
Yes, that makes more sense!

2024-02-20 12:24 UTC, merged