84 simplify checksum in sync
UtrechtUniversity/iBridges pull request #88
Opened 2024-03-21 15:49 UTC by maartenschermer

Reduced the number of checksum parameters.

2024-03-28 09:36 UTC, qubixes approved these changes
Nice, looks much more elegant this way!

2024-03-28 09:36 UTC, qubixes commented on tutorials/Data_sync.ipynb
> +    "- The `verify_checksum` (default True) option will calculate and verify the checksum on the data after up- or downloading. A checksum mismatch will generate an error, aborting the synchronizatio
Maybe it would be nice to give some instruction on how to deal with this situation?

2024-04-02 07:57 UTC, chStaiger requested changes
Much nicer!!! And indeed checksums should be always obeyed ;)

Can you please fix the integration tests? Then it is ready for approval.

2024-04-02 09:07 UTC, maartenschermer commented
I fixed the tutorial and the integration test, but there seems to be a linting issue in the metadata. Shall I fix that too, or have they already been fixed in develop?

2024-04-02 09:51 UTC, qubixes commented
> I fixed the tutorial and the integration test, but there seems to be a linting issue in the metadata. Shall I fix that too, or have they already been fixed in develop?

You can ignore the 3.8 linting errors they are fixed in #89

2024-04-02 09:54 UTC, merged